/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsMain.formsAdmin;

import Users.userAdmin.AddDoctor;
import Users.userAdmin.RemoveDoctor;
import java.util.Objects;
import javax.swing.JOptionPane;

/**
 *
 * @author Zack
 */
public class AddRemoveDoctors extends javax.swing.JFrame {

    /**
     * Creates new form AddRemoveSecDoc
     */
    public AddRemoveDoctors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblDesiredPasswd = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        lblConfirmPassword = new javax.swing.JLabel();
        txtconfirmPassword = new javax.swing.JTextField();
        RadBtnadd = new javax.swing.JRadioButton();
        RadBtnremove = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnremAcc = new javax.swing.JButton();
        lblAddress = new javax.swing.JLabel();
        lblDesiredUname = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        txtuserName = new javax.swing.JTextField();
        btnaddAcc = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        chxbxconfirmTerm = new javax.swing.JCheckBox();

        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDesiredPasswd.setText("Password :");

        lblConfirmPassword.setText("Confirm Password :");

        RadBtnadd.setSelected(true);
        RadBtnadd.setText("Add");
        RadBtnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadBtnaddMouseClicked(evt);
            }
        });
        RadBtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBtnaddActionPerformed(evt);
            }
        });

        RadBtnremove.setText("Remove");
        RadBtnremove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadBtnremoveMouseClicked(evt);
            }
        });
        RadBtnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBtnremoveActionPerformed(evt);
            }
        });

        jLabel1.setText("Add / Remove Doctors ");

        btnremAcc.setText("Remove Account");
        btnremAcc.setEnabled(false);
        btnremAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnremAccMouseClicked(evt);
            }
        });

        lblAddress.setText("Address :");

        lblDesiredUname.setText("Name :");

        btnaddAcc.setText("Add Account");
        btnaddAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddAccMouseClicked(evt);
            }
        });
        btnaddAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddAccActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        chxbxconfirmTerm.setText("Are you sure you want to terminate your account?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(lblDesiredUname)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtuserName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RadBtnadd)
                                        .addComponent(RadBtnremove))
                                    .addGap(87, 87, 87)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDesiredPasswd)
                                    .addComponent(lblAddress)
                                    .addComponent(lblConfirmPassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(txtpassword)
                                    .addComponent(txtconfirmPassword))))
                        .addGap(0, 150, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(chxbxconfirmTerm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnremAcc))
                            .addComponent(btnaddAcc, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnback)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnback))
                .addGap(15, 15, 15)
                .addComponent(RadBtnadd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadBtnremove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDesiredUname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesiredPasswd)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmPassword)
                    .addComponent(txtconfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btnaddAcc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnremAcc)
                    .addComponent(chxbxconfirmTerm))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadBtnaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadBtnaddMouseClicked
        // TODO add your handling code here:
        btnremAcc.setEnabled(false);
        btnaddAcc.setEnabled(true);
        txtaddress.setEnabled(true);
        RadBtnremove.setSelected(false);
    }//GEN-LAST:event_RadBtnaddMouseClicked

    private void RadBtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBtnaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadBtnaddActionPerformed

    private void RadBtnremoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadBtnremoveMouseClicked
        // TODO add your handling code here:
        btnremAcc.setEnabled(true);
        btnaddAcc.setEnabled(false);
        txtaddress.setEnabled(false);
        RadBtnadd.setSelected(false);
    }//GEN-LAST:event_RadBtnremoveMouseClicked

    private void RadBtnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBtnremoveActionPerformed
        // TODO add your handling code here:
        
       ;
    }//GEN-LAST:event_RadBtnremoveActionPerformed

    private void btnaddAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddAccActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        new AdminHomeScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        // TODO add your handling code here:
        new AdminHomeScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackMouseClicked

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnremAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnremAccMouseClicked
        // TODO add your handling code here:
        if (Objects.equals(txtpassword.getText(),txtconfirmPassword.getText())){
            if (chxbxconfirmTerm.isSelected()){
                String name = txtuserName.getText();
                RemoveDoctor r = new RemoveDoctor();
                r.removeAccount(name);
                JOptionPane.showMessageDialog(null, "Doctor successfully deleted!", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                txtpassword.setText("");
                txtconfirmPassword.setText("");
                txtaddress.setText("");
                txtuserName.setText("");
                chxbxconfirmTerm.setSelected(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Make sure to tick are you sure want to terminate your account", "Ok", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Passwords do not match", "Ok", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnremAccMouseClicked

    private void btnaddAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddAccMouseClicked
        // TODO add your handling code here:
        if (Objects.equals(txtpassword.getText(),txtconfirmPassword.getText())){
            String name = txtuserName.getText();
            String address = txtaddress.getText();
            String password = txtpassword.getText();
            AddDoctor a = new AddDoctor();
            a.CreateNewAccount(password, address, name);
            JOptionPane.showMessageDialog(null, "Account successfully created.", "Ok", JOptionPane.INFORMATION_MESSAGE);
            
            txtpassword.setText("");
            txtconfirmPassword.setText("");
            txtaddress.setText("");
            txtuserName.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Passwords do not match", "Ok", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnaddAccMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRemoveDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRemoveDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRemoveDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRemoveDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRemoveDoctors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadBtnadd;
    private javax.swing.JRadioButton RadBtnremove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnaddAcc;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnremAcc;
    private javax.swing.JCheckBox chxbxconfirmTerm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblDesiredPasswd;
    private javax.swing.JLabel lblDesiredUname;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtconfirmPassword;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtuserName;
    // End of variables declaration//GEN-END:variables
}
