/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsMain.formsAdmin;

import formsMain.HomeScreen;

/**
 *
 * @author Zack
 */
public class AdminHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminHomeScreen
     */
    public AdminHomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btncreateAcc = new javax.swing.JButton();
        btnaddRem = new javax.swing.JButton();
        btnprovideFeedback = new javax.swing.JButton();
        btnlogOff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Admin Home Screen");

        btncreateAcc.setText("Create admin account");
        btncreateAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncreateAccMouseClicked(evt);
            }
        });

        btnaddRem.setText("Add / Remove Doctors / Secretaries");
        btnaddRem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddRemMouseClicked(evt);
            }
        });

        btnprovideFeedback.setText("Provide feedback for Doctors and view ratings");
        btnprovideFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprovideFeedbackMouseClicked(evt);
            }
        });

        btnlogOff.setText("Log Off");
        btnlogOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogOffMouseClicked(evt);
            }
        });
        btnlogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogOffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnaddRem)
                    .addComponent(jLabel1)
                    .addComponent(btncreateAcc)
                    .addComponent(btnprovideFeedback))
                .addGap(0, 55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlogOff)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(btnaddRem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncreateAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnprovideFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnlogOff)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogOffMouseClicked
        // TODO add your handling code here:
        new HomeScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlogOffMouseClicked

    private void btnlogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogOffActionPerformed

    private void btnaddRemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddRemMouseClicked
        // TODO add your handling code here:
        new AddRemoveSecDoc().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaddRemMouseClicked

    private void btncreateAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncreateAccMouseClicked
        // TODO add your handling code here:
        new CreateOwnAccount().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncreateAccMouseClicked

    private void btnprovideFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprovideFeedbackMouseClicked
        // TODO add your handling code here:
        new ProvideFeedbackandViewRatings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnprovideFeedbackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddRem;
    private javax.swing.JButton btncreateAcc;
    private javax.swing.JButton btnlogOff;
    private javax.swing.JButton btnprovideFeedback;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
