/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsMain.formsDoctor;

import formsMain.HomeScreen;

/**
 *
 * @author Zack
 */
public class DoctorHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form DoctorHomeScreen
     */
    public DoctorHomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btncreateAppointment = new javax.swing.JButton();
        btnorderMeds = new javax.swing.JButton();
        btnlogoff1 = new javax.swing.JButton();
        btnconsult = new javax.swing.JButton();
        btnvFeedback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Doctor HomeScreen");

        btncreateAppointment.setText("Create appointment");
        btncreateAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncreateAppointmentMouseClicked(evt);
            }
        });

        btnorderMeds.setText("Order medicine");
        btnorderMeds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnorderMedsMouseClicked(evt);
            }
        });
        btnorderMeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderMedsActionPerformed(evt);
            }
        });

        btnlogoff1.setText("Log off");
        btnlogoff1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoff1MouseClicked(evt);
            }
        });

        btnconsult.setText("Consult");
        btnconsult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnconsultMouseClicked(evt);
            }
        });

        btnvFeedback.setText("View your feedback");
        btnvFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvFeedbackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnlogoff1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btncreateAppointment)
                            .addComponent(btnorderMeds)
                            .addComponent(btnconsult)
                            .addComponent(btnvFeedback))
                        .addGap(0, 251, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btncreateAppointment)
                .addGap(18, 18, 18)
                .addComponent(btnorderMeds)
                .addGap(18, 18, 18)
                .addComponent(btnconsult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnvFeedback)
                .addGap(46, 46, 46)
                .addComponent(btnlogoff1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnorderMedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderMedsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnorderMedsActionPerformed

    private void btnlogoff1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoff1MouseClicked
        // TODO add your handling code here:
        new HomeScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlogoff1MouseClicked

    private void btncreateAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncreateAppointmentMouseClicked
        // TODO add your handling code here:
        new FCreateAppointments().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncreateAppointmentMouseClicked

    private void btnorderMedsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnorderMedsMouseClicked
        // TODO add your handling code here:
        new CreateMedsOrder().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnorderMedsMouseClicked

    private void btnconsultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconsultMouseClicked
        // TODO add your handling code here:
        new Consult().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnconsultMouseClicked

    private void btnvFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvFeedbackMouseClicked
        // TODO add your handling code here:
        new FViewOwnFeedback().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvFeedbackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorHomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsult;
    private javax.swing.JButton btncreateAppointment;
    private javax.swing.JButton btnlogoff1;
    private javax.swing.JButton btnorderMeds;
    private javax.swing.JButton btnvFeedback;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
