/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsMain.formsSecretary;

import Users.userSecretary.ApproveAccounts;
import Users.userSecretary.ApproveAppointment;
import Users.userSecretary.ViewAppointment;
import Users.userSecretary.ViewTempUsers;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Zack
 */
public class FApproveAppointment extends javax.swing.JFrame {

    /**
     * Creates new form FApproveAppointment
     */
    public FApproveAppointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbxdate = new javax.swing.JComboBox<>();
        lblFormTitle = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        btnapprove = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txbxpatientInfo = new javax.swing.JTextArea();
        btndeny = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        cmbxdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxdateActionPerformed(evt);
            }
        });

        lblFormTitle.setText("Approve Appointment");

        lblPatientName.setText("Date:");

        btnapprove.setText("Approve");
        btnapprove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnapproveMouseClicked(evt);
            }
        });
        btnapprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapproveActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });

        txbxpatientInfo.setColumns(20);
        txbxpatientInfo.setRows(5);
        jScrollPane1.setViewportView(txbxpatientInfo);

        btndeny.setText("Deny");
        btndeny.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndenyMouseClicked(evt);
            }
        });
        btndeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndenyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnapprove))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFormTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnback))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPatientName)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbxdate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                                .addComponent(btndeny)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormTitle)
                    .addComponent(btnback))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbxdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndeny))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnapprove)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbxdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxdateActionPerformed
        // TODO add your handling code here:
        ViewAppointment v = new ViewAppointment();
        String userdata = v.GetAppointment(cmbxdate.getSelectedItem().toString());
        txbxpatientInfo.setText(userdata);

    }//GEN-LAST:event_cmbxdateActionPerformed

    private void btnapproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapproveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnapproveActionPerformed

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        // TODO add your handling code here:
        new SecretaryHomeScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackMouseClicked

    private void btndenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndenyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndenyActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ApproveAppointment a = new ApproveAppointment();
        ArrayList<String> assign = new ArrayList<String>();
        assign = a.GetAppointments();
        
        for (int i = 0; i < assign.size(); i++){
            cmbxdate.addItem(assign.get(i));
        }
        
        ViewAppointment v = new ViewAppointment();
        String userdata = v.GetAppointment(cmbxdate.getSelectedItem().toString());
        txbxpatientInfo.setText(userdata);
    }//GEN-LAST:event_formWindowActivated

    private void btnapproveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnapproveMouseClicked
        // TODO add your handling code here:
        String date = cmbxdate.getSelectedItem().toString();
        ApproveAppointment a = new ApproveAppointment();
        a.AddAppointment(date);
        
        JOptionPane.showMessageDialog(null, "Appointment request accepted!", "Ok", JOptionPane.INFORMATION_MESSAGE);
        
        new SecretaryHomeScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnapproveMouseClicked

    private void btndenyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndenyMouseClicked
        // TODO add your handling code here:
        String date = cmbxdate.getSelectedItem().toString();
        ApproveAppointment a = new ApproveAppointment();
        a.RemoveAppointment(date);
        
        JOptionPane.showMessageDialog(null, "Appointment request denied!", "Ok", JOptionPane.INFORMATION_MESSAGE);
        
        new SecretaryHomeScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndenyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FApproveAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FApproveAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FApproveAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FApproveAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FApproveAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnapprove;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndeny;
    private javax.swing.JComboBox<String> cmbxdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFormTitle;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JTextArea txbxpatientInfo;
    // End of variables declaration//GEN-END:variables
}
