/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsMain.formsSecretary;

import Users.userSecretary.GiveMeds;
import Users.userSecretary.ViewPrescription;
import Users.userSecretary.GetPatientPrescriptions;
import java.util.ArrayList;
import javax.swing.JOptionPane;





/**
 *
 * @author Zack
 */
public class FGiveMeds extends javax.swing.JFrame {

    /**
     * Creates new form GiveMeds
     */
    public FGiveMeds() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPatientName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnconfirm = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        cmbxpatientID = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtprescrition = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        cmbxmeds = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblPatientName.setText("Patient ID:");

        jLabel1.setText("Give Medicine to Patient");

        btnconfirm.setText("Confirm");
        btnconfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnconfirmMouseClicked(evt);
            }
        });

        btnback.setText("Back");
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });

        cmbxpatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxpatientIDActionPerformed(evt);
            }
        });

        txtprescrition.setColumns(20);
        txtprescrition.setRows(5);
        jScrollPane1.setViewportView(txtprescrition);

        jLabel2.setText("Prescription:");

        cmbxmeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxmedsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                        .addComponent(btnback))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnconfirm))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(lblPatientName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbxpatientID, 0, 82, Short.MAX_VALUE)
                                    .addComponent(cmbxmeds, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnback))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(cmbxpatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbxmeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnconfirm)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        // TODO add your handling code here:
        new SecretaryHomeScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        cmbxpatientID.removeAllItems();
        cmbxmeds.removeAllItems();
        
        
        GiveMeds p = new GiveMeds();
        ArrayList <String> assign = new ArrayList<String>();
        assign = p.GetMeds();
        
        for (int i = 0; i < assign.size(); i++){
            cmbxpatientID.addItem(assign.get(i));
        }
        
        GetPatientPrescriptions g = new GetPatientPrescriptions();
        ArrayList <String> assign2 = new ArrayList<String>();
        assign2 = g.GetPatientPresc(cmbxpatientID.getSelectedItem().toString());
        
        for (int i = 0; i < assign2.size(); i++){
            cmbxmeds.addItem(assign2.get(i));
        }
        
        ViewPrescription v = new ViewPrescription();
        String userdata = v.getprescription(cmbxpatientID.getSelectedItem().toString(), cmbxmeds.getSelectedItem().toString());
        txtprescrition.setText(userdata);
    }//GEN-LAST:event_formWindowActivated

    private void cmbxpatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxpatientIDActionPerformed
        // TODO add your handling code here:
        
        
        cmbxmeds.removeAllItems();
        GetPatientPrescriptions g = new GetPatientPrescriptions();
        ArrayList <String> assign2 = new ArrayList<String>();
        assign2 = g.GetPatientPresc(cmbxpatientID.getSelectedItem().toString());
        
        for (int i = 0; i < assign2.size(); i++){
            cmbxmeds.addItem(assign2.get(i));
        }
        
        ViewPrescription v = new ViewPrescription();
        String userdata = v.getprescription(cmbxpatientID.getSelectedItem().toString(),cmbxmeds.getSelectedItem().toString());
        txtprescrition.setText(userdata);
    }//GEN-LAST:event_cmbxpatientIDActionPerformed

    private void btnconfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfirmMouseClicked
        // TODO add your handling code here:
        String userID = cmbxpatientID.getSelectedItem().toString();
        String med = cmbxmeds.getSelectedItem().toString();
        GiveMeds g = new GiveMeds();
        g.GiveMeds(userID,med);
        
        JOptionPane.showMessageDialog(null, "Medicine prescribed!", "Ok", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnconfirmMouseClicked

    private void cmbxmedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxmedsActionPerformed
        // TODO add your handling code here:
        ViewPrescription v = new ViewPrescription();
        String userdata = v.getprescription(cmbxpatientID.getSelectedItem().toString(),cmbxmeds.getSelectedItem().toString());
        txtprescrition.setText(userdata);
    }//GEN-LAST:event_cmbxmedsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FGiveMeds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FGiveMeds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FGiveMeds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FGiveMeds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FGiveMeds().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnconfirm;
    private javax.swing.JComboBox<String> cmbxmeds;
    private javax.swing.JComboBox<String> cmbxpatientID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JTextArea txtprescrition;
    // End of variables declaration//GEN-END:variables
}
