/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsMain.formsSecretary;

import formsMain.HomeScreen;

/**
 *
 * @author Zack
 */
public class SecretaryHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form SecretaryHomeScreen
     */
    public SecretaryHomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnappDenyRequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnapproveApp = new javax.swing.JButton();
        btngiveMeds = new javax.swing.JButton();
        btnappRemovalReq = new javax.swing.JButton();
        btnlogoff1 = new javax.swing.JButton();
        btncreateApp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnappDenyRequest.setText("Approve / Deny Patient account requests");
        btnappDenyRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnappDenyRequestMouseClicked(evt);
            }
        });

        jLabel1.setText("Secretary HomeScreen");

        btnapproveApp.setText("Approve appointment");
        btnapproveApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnapproveAppMouseClicked(evt);
            }
        });

        btngiveMeds.setText("Give medicine to Patient");
        btngiveMeds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngiveMedsMouseClicked(evt);
            }
        });

        btnappRemovalReq.setText("Approve Patient account removal");
        btnappRemovalReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnappRemovalReqMouseClicked(evt);
            }
        });

        btnlogoff1.setText("Log off");
        btnlogoff1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoff1MouseClicked(evt);
            }
        });

        btncreateApp.setText("Create appointment");
        btncreateApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncreateAppMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnlogoff1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnappDenyRequest)
                            .addComponent(btnappRemovalReq)
                            .addComponent(btngiveMeds)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btncreateApp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnapproveApp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 149, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(btnappDenyRequest)
                .addGap(18, 18, 18)
                .addComponent(btnappRemovalReq)
                .addGap(18, 18, 18)
                .addComponent(btnapproveApp)
                .addGap(18, 18, 18)
                .addComponent(btncreateApp)
                .addGap(18, 18, 18)
                .addComponent(btngiveMeds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnlogoff1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoff1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoff1MouseClicked
        // TODO add your handling code here:
        new HomeScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlogoff1MouseClicked

    private void btnappDenyRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnappDenyRequestMouseClicked
        // TODO add your handling code here:
        new ApprovePatientAccounts().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnappDenyRequestMouseClicked

    private void btnappRemovalReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnappRemovalReqMouseClicked
        // TODO add your handling code here:
        new ApprovePatientAccountRemovalRequests().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnappRemovalReqMouseClicked

    private void btnapproveAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnapproveAppMouseClicked
        // TODO add your handling code here:
        new FApproveAppointment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnapproveAppMouseClicked

    private void btngiveMedsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngiveMedsMouseClicked
        // TODO add your handling code here:
        new GiveMeds().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btngiveMedsMouseClicked

    private void btncreateAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncreateAppMouseClicked
        // TODO add your handling code here:
        new FCreateAppointment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncreateAppMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretaryHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretaryHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretaryHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretaryHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretaryHomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnappDenyRequest;
    private javax.swing.JButton btnappRemovalReq;
    private javax.swing.JButton btnapproveApp;
    private javax.swing.JButton btncreateApp;
    private javax.swing.JButton btngiveMeds;
    private javax.swing.JButton btnlogoff1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
